# Generated by Django 4.0.4 on 2022-04-30 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_birthday_alter_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Password must be combination of Uppercase, Lowercase, Special Characters and Digits.', regex='^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])[a-zA-Z\\d@$.!%*#?&]')]),
        ),
    ]
