# Generated by Django 4.0.4 on 2022-05-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
