# Generated by Django 4.0.4 on 2022-05-08 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='projects/static/images'),
            preserve_default=False,
        ),
    ]
