# Generated by Django 4.0.4 on 2022-05-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_donations_project_donation_projectdonation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='donation',
        ),
    ]
