# Generated by Django 4.0.4 on 2022-05-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrateproject',
            name='rate',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Verygood'), (5, 'Excellent')]),
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
