# Generated by Django 4.0.4 on 2022-05-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='projects/static/projects/images'),
        ),
    ]
