# Generated by Django 4.0.4 on 2022-05-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_is_canceled'),
        ('projects', '0005_comment_comment_reports_comment_created_and_more'),
    ]

    operations = [
    ]
