# Generated by Django 4.0.4 on 2022-05-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_merge_20220507_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='donations',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=19),
        ),
    ]
