# Generated by Django 4.0.4 on 2022-05-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_merge_20220507_0015'),
        ('projects', '0008_remove_project_donations'),
    ]

    operations = [
    ]
