# Generated by Django 4.0.4 on 2022-05-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_merge_20220507_1617'),
        ('projects', '0009_merge_20220507_1922'),
    ]

    operations = [
    ]
